In [1]:
import numpy as np

In [2]:
from numpy import genfromtxt
data = genfromtxt('bank_note_data.txt', delimiter=',')

In [3]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [4]:
labels = data[:,4]

In [5]:
features = data[:,0:4]

In [6]:
X = features
y = labels

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [9]:
X_train

array([[-0.8734  , -0.033118, -0.20165 ,  0.55774 ],
       [ 2.0177  ,  1.7982  , -2.9581  ,  0.2099  ],
       [-0.36038 ,  4.1158  ,  3.1143  , -0.37199 ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

In [10]:
X_test

array([[ 1.5691  ,  6.3465  , -0.1828  , -2.4099  ],
       [-0.27802 ,  8.1881  , -3.1338  , -2.5276  ],
       [ 0.051979,  7.0521  , -2.0541  , -3.1508  ],
       ...,
       [ 3.5127  ,  2.9073  ,  1.0579  ,  0.40774 ],
       [ 5.504   , 10.3671  , -4.413   , -4.0211  ],
       [-0.2062  ,  9.2207  , -3.7044  , -6.8103  ]])

In [11]:
y_train

array([1., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 1., 1., 0.,
       1., 1., 1., 0., 1., 1., 1., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0.,
       1., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1.,
       0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 1.,
       1., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1.,
       0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 0.,
       1., 0., 0., 1., 0.

In [12]:
from sklearn.preprocessing import MinMaxScaler

In [13]:
scaler_object = MinMaxScaler()

In [14]:
scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [15]:
scaled_X_train = scaler_object.transform(X_train)

In [16]:
scaled_X_test = scaler_object.transform(X_test)

In [17]:
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [18]:
# Creates model
model = Sequential()
# 8 Neurons, expects input of 4 features. 
# Play around with the number of neurons!!
model.add(Dense(4, input_dim=4, activation='relu'))
# Add another Densely Connected layer (every neuron connected to every neuron in the next layer)
model.add(Dense(8, activation='relu'))
# Last layer simple sigmoid function to output 0 or 1 (our label)
model.add(Dense(1, activation='sigmoid'))

In [19]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [20]:
# Play around with number of epochs as well!
model.fit(scaled_X_train,y_train,epochs=20, verbose=2)

Epoch 1/20
 - 1s - loss: 0.6896 - acc: 0.5332
Epoch 2/20
 - 0s - loss: 0.6803 - acc: 0.5495
Epoch 3/20
 - 0s - loss: 0.6740 - acc: 0.5495
Epoch 4/20
 - 0s - loss: 0.6683 - acc: 0.5495
Epoch 5/20
 - 0s - loss: 0.6623 - acc: 0.5495
Epoch 6/20
 - 0s - loss: 0.6549 - acc: 0.5495
Epoch 7/20
 - 0s - loss: 0.6462 - acc: 0.5495
Epoch 8/20
 - 0s - loss: 0.6358 - acc: 0.5495
Epoch 9/20
 - 0s - loss: 0.6239 - acc: 0.5658
Epoch 10/20
 - 0s - loss: 0.6109 - acc: 0.5898
Epoch 11/20
 - 0s - loss: 0.5949 - acc: 0.6551
Epoch 12/20
 - 0s - loss: 0.5744 - acc: 0.6964
Epoch 13/20
 - 0s - loss: 0.5549 - acc: 0.7356
Epoch 14/20
 - 0s - loss: 0.5360 - acc: 0.7769
Epoch 15/20
 - 0s - loss: 0.5167 - acc: 0.7922
Epoch 16/20
 - 0s - loss: 0.4981 - acc: 0.8118
Epoch 17/20
 - 0s - loss: 0.4793 - acc: 0.8313
Epoch 18/20
 - 0s - loss: 0.4609 - acc: 0.8335
Epoch 19/20
 - 0s - loss: 0.4424 - acc: 0.8542
Epoch 20/20
 - 0s - loss: 0.4219 - acc: 0.8629


In [21]:
model.predict_classes(scaled_X_test)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
    

In [22]:
model.evaluate(x=scaled_X_test,y=y_test)

453/453 [==============================] - 0s 191us/step


[0.4136287623288616, 0.8631346578366446]

In [23]:
from sklearn.metrics import confusion_matrix,classification_report

In [24]:
predictions = model.predict_classes(scaled_X_test)

In [25]:
confusion_matrix(y_test,predictions)

array([[253,   4],
       [ 58, 138]], dtype=int64)

In [26]:
print(classification_report(y_test,predictions))

             precision    recall  f1-score   support

        0.0       0.81      0.98      0.89       257
        1.0       0.97      0.70      0.82       196

avg / total       0.88      0.86      0.86       453



In [29]:
model.save('myfirstmodel.h5')

In [30]:
from keras.models import load_model

In [31]:
newmodel = load_model('myfirstmodel.h5')